### ISSUE TITLE
Crash on open when LNC node selected as default.

### ISSUE THREAD

**Issue by dadofsambonzuki** [ZeusLN/zeus#1336] opened 2023-02-20 13:35 UTC
### Describe the bug

Been doing a lot of zapping on nostr and have noticed that Zeus crashes on start-up if an LNC connected node is selected.

If Zeus is already unlocked, it does not crash.

If Alby is selected as my node then Zeus starts fine from a cold start.

### Reproduce

As per description.

### Zeus version

v0.7.3

### Node interface

Multiple (specified in comments)

### Network

Clearnet

### Device

Pixel 5a

### Device operating system

Android 13

**Comment by myxmaster** [comment] 2023-02-23 10:19
probably a duplicate of this: https://github.com/ZeusLN/zeus/issues/1278

**Comment by kaloudis** [comment] 2023-03-01 02:21
@myxmaster I'm not convinced it's quite the same issue. Shouldn't be having the init issue with LND REST but we'll find out. Fix is linked above.

**Comment by dadofsambonzuki** [comment] 2023-03-04 08:33
Confirmed fixed in latest rc.

This is why open source will rule the world. 🤙

**Closed** 2023-03-04 08:34 UTC
Labels: Bug
