### ISSUE TITLE
Incorrect balance shown on profile switch

### ISSUE THREAD

**Issue by Swissnode** [ZeusLN/zeus#207] opened 2020-01-18 15:46 UTC
This bug shows an incorrect balance for onchain and offchain totals when user switches profile

**Steps to reproduce the behavior**
1. Have more than one node set up on Zeus. This case used two lnd nodes
2. Assuming the current node is the first node A, switch to second node B. The balances here seem correct
3. Switch back to the first profile A and select "set node config as active"

**Expected behaviour**
You expect the original values of node A to be shown

**Actual behaviour**
The channel balance is that of node B (incorrect) and the onchain wallet balance is shown as 0

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: latest at time of writing
 - Zeus Version v0.2.0

**Additional context**
Refreshing by swiping down in the main screen fixes the issue

**Comment by kaloudis** [comment] 2020-01-20 18:56
This should be alleviated by https://github.com/ZeusLN/zeus/pull/215 - let's see!

**Comment by mjlamb** [comment] 2020-02-14 01:58
I've had this same problem I'll retest with v0.2.1 and see if this still occurs.

**Comment by mjlamb** [comment] 2020-02-14 05:32
I can confirm that I have 2 nodes setup and balances are currently showing correct using v0.2.1

**Comment by Swissnode** [comment] 2020-02-17 07:50
@mjlamb I still have problems, can you try switChing back and forth between nodes? I get non-deterministic incorrect values, which sometimes are corrected with a refresh...

**Comment by mjlamb** [comment] 2020-02-17 07:59
Actually you are correct I have done some more testing and on first look it seemed good, but switching between them does eventually cause balances to show incorrectly.

**Comment by mjlamb** [comment] 2020-02-17 08:19
For me it is actually the "On-chain" tab that does not update correctly.

**Comment by ZeusLN** [comment] 2020-08-18 04:48
Is this still an issue y'all are experiencing?

**Comment by mjlamb** [comment] 2020-08-28 10:03
Seems to be ok now switching between nodes.

**Comment by ZeusLN** [comment] 2020-11-03 04:47
Fixed in v0.2.1, I believe. Please re-open if this reoccurs

**Closed by ZeusLN** 2020-11-03 04:47 UTC
