### ISSUE TITLE
Display option - all time routing sats earned

### ISSUE THREAD

**Issue by NEEDcreations** [ZeusLN/zeus#1993] opened 2024-02-22 17:19 UTC
### Describe the feature

Currently, we can only view up to the last year of total routing sats earned. I'd like to see my all time routing sats earned.

**Comment by kaloudis** [comment] 2024-02-22 17:19
Duplicate of https://github.com/ZeusLN/zeus/issues/1715

**Closed by kaloudis** 2024-02-22 17:19 UTC
Labels: Feature request

**Comment by NEEDcreations** [comment] 2024-02-22 17:56
oops lol I forgot I already requested this feature. Sorry!
