### ISSUE TITLE
On-chain withdraw should have a "Max" button that sweeps the full balance.

### ISSUE THREAD

**Issue by cmdruid** [ZeusLN/zeus#1052] opened 2022-07-27 23:41 UTC
### Describe the feature

The wallet does not appear to reserve the fee required to sweep the on-chain balance on the wallet, meaning you have to calculate the fee manually and subtract it from the max balance amount, which is hard to do without seeing the raw transaction.

It would be nice to have a "Max" button that pre-calculates the real max withdraw-able amount (taking the sats/vB setting into account), and sweeps all funds from the on-chain balance.

**Comment by kaloudis** [comment] 2023-01-04 02:13
Duplicate of https://github.com/ZeusLN/zeus/issues/201

Targeting v0.8

**Closed by kaloudis** 2023-01-04 02:13 UTC
Labels: Feature request
