### ISSUE TITLE
[iOS/BTCPay] Can't add a node

### ISSUE THREAD

**Issue by Sosthene00** [ZeusLN/zeus#98] opened 2019-06-03 23:51 UTC
**Describe the bug**
I can't connect to my LND node that is running inside a BTCPay

**To Reproduce**
1. Go to settings
2. On BTCPay, find the LND REST Qr code
3. Scan the Qr code
4. Copy paste the info

**Expected behavior**
I should connect to my LND

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser [e.g. chrome, safari] : firefox
 - Version [e.g. 22] 66.0.4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 6S
 - OS: [e.g. iOS8.1] 12.1.3
 - Browser [e.g. stock browser, safari] firefox

**Additional context**

**Comment by kaloudis** [comment] 2019-06-04 16:01
@BobleChinois  thanks for the report. What version of Zeus are you running?

**Comment by kaloudis** [comment] 2019-06-05 01:04
Found the bug earlier. This should be fixed in v0.1.0-beta-2 https://github.com/ZeusLN/zeus/releases/tag/v0.1.0-beta-2

**Comment by BobleChinois** [comment] 2019-06-05 16:43
Hi, thanks for the answer, I updated Zeus with Testflight, but now it's even worse because I can't scan the QR code at all (nothing happens).

I forgot to add that my BTCPay version is v1.0.3.112, I don't know if it's relevant

**Comment by ZeusLN** [comment] 2020-08-18 04:30
@Sosthene00 can you try again with v0.3.1? Thanks

**Comment by Sosthene00** [comment] 2020-08-20 16:30
Hi, sorry I killed my BTCPay I don't have one handy right now. If I can find a friend with one I'll try again

**Comment by uhlhosting** [comment] 2021-03-01 07:27
Hi, it seems the issue is simple, either the QR code does not sent the FQDN or the Zeus does not read it, I have the exact same issues doing following:

- Login to BTC pay server, go to Services
- here we can see the right URL from the QR details on BTCpay
- next when the URL is scannel, the webpage will be pulled into Zeus without `https://` protocol, thus showing RED status
- Would be great to solve this.
- Using latest Beta iOS / iPhone XR / BTCPay Dockerized via Ubuntu 20.04
- note that just adding the missing `https://` it will work in my case.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/6324047/109464833-9a11a580-7a67-11eb-9ed6-e2394158f4d0.png">

**Closed** 2021-05-06 16:21 UTC
