### ISSUE TITLE
Android ZeusLN app crashes with GrapheneOS - Memory Tagging feature enabled

### ISSUE THREAD

**Issue by emtreulapollaguera** [ZeusLN/zeus#2229] opened 2024-06-09 14:15 UTC
### Describe the bug

By default, memory tagging feature is enabled for all apps in GrapheneOS. ZeusLN crashes if this feature is not disabled. This scenario is not ideal and increase vulnearibility riskes by forcing user to disable the feature to be able to run the ZeusLN app.

Any possibility to fix this?

I experienced the issue in a Pixel 8 with GrapheneOS version 2024060500.

Graphene OS logs report can be attached if required.

Thank you!
![IMG_20240609_161016](https://github.com/ZeusLN/zeus/assets/162636267/bceb44ac-86f6-46f1-bcf1-f25fc70a44a0)
![IMG_20240609_161200](https://github.com/ZeusLN/zeus/assets/162636267/82399600-5c03-456a-a2d3-119073118a31)

### Reproduce

Reproduce the bug step by step.

### ZEUS version

v0.8.4

### Node interface

Embedded LND

### Network

Tor

### Device

Pixel 8

### Device operating system

Graphene OS

### Log output

```shell
type: crash
osVersion: google/shiba/shiba:14/AP1A.240505.005/2024060500:user/release-keys
uid: 10153 (u:r:untrusted_app:s0:c153,c256,c512,c768)
cmdline: app.zeusln.zeus
processUptime: 27s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr e00d74563f5a740
threadName: Thread-1
MTE: enabled

backtrace:
    /data/app/~~6-cTzSupYJjxZaq-eoGSUg==/app.zeusln.zeus-Foqj8LRw5bIfRHZYB6IdgQ==/lib/arm64/libgojni.so (pc 45e808)
```
```

**Comment by kaloudis** [comment] 2024-06-09 15:55
duplicate of https://github.com/ZeusLN/zeus/issues/1872

**Closed** 2024-07-13 02:34 UTC
Labels: Bug
