### ISSUE TITLE
LNURLp & LNURLw causing app to crash

### ISSUE THREAD

**Issue by thecharacter** [ZeusLN/zeus#578] opened 2021-09-07 19:47 UTC
Love the app ya'll
I found whenever I scan a LNURLp or a LNURLw QR code generated from LNbits.com the app returns an error and causes the app to crash. I tested the same QR codes against Bluewallet and they worked. 

I'm using a Iphone running 0.12.1-beta LND, Zeus version v0.6.0 alpha2

![IMG_E6A9731DE9BB-1](https://user-images.githubusercontent.com/70460811/132401657-9e5fe980-6b6c-47c9-8fc2-b5e29275349a.jpeg)

**Comment by pseudozach** [comment] 2021-09-27 20:42
I'm unable to reproduce this with any lnurlp/lnurlw string from lnbits. Even tried with the URL you mentioned here. Zeus is not crashing. 
Maybe it was an intermittent issue and lnbits returned something strange temporarily. Please share if you still encounter this.

**Comment by thecharacter** [comment] 2021-09-28 21:25
Thanks for checking in on this issue. Here is the LNURL in question that causing Zeus to return an error. When scanning the LNURL the error message above loads ( it generates at least 34 times) multiple times. If I click OK on the error message 34 times the screen eventually appears where you can actually pay the invoice. Here's an unlisted video on youtube of what's actually happening. The LNURLp is below.

https://youtu.be/wGhCsLbjLQs

![Screen Shot 2021-09-28 at 1 22 51 PM](https://user-images.githubusercontent.com/70460811/135162666-6d0660e3-df1b-4f16-9bfb-ac2ea70faccf.png)

**Comment by pseudozach** [comment] 2021-09-28 21:53
This QR code reads OK on Android 11, Zeus v0.5.2 but I was able to see the same issue on Alpha2. Will look into this. Thanks for the detailed report!

**Comment by kaloudis** [comment] 2021-12-01 04:35
Fixed in v0.6.0-alpha4 https://github.com/ZeusLN/zeus/releases/tag/v0.6.0-alpha4

**Closed by kaloudis** 2021-12-01 04:35 UTC
