### ISSUE TITLE
Channel sort option: Open height

### ISSUE THREAD

**Issue by NEEDcreations** [ZeusLN/zeus#2090] opened 2024-03-27 16:28 UTC
### Describe the feature

It'd be nice to be able to sort our channels by their open height, similar to the new "close height" feature.

**Comment by kaloudis** [comment] 2024-03-27 23:00
Dupe of https://github.com/ZeusLN/zeus/issues/1713

Not sure this is currently possible without some changes upstream in LND, as commented on the issue linked above. Perhaps worth opening up a ticket in their repo asking for it to be returned on the channel object

**Closed by kaloudis** 2024-03-27 23:00 UTC
Labels: Feature request
